notifications:
  email: false

sudo: false

addons:
  apt:
    packages:
      - stunnel4

language: php

php:
  - 7.1
  - 7.2
  - 7.3

env:
  matrix:
    -
    - DEPENDENCIES=--prefer-lowest

matrix:
  fast_finish: true

cache:
  directories:
    - vendor

install:
  - composer validate
  - composer --no-interaction update $DEPENDENCIES

script:
  - composer test -- --coverage-clover=build/logs/clover.xml --coverage-xml=build/coverage/coverage-xml
    --log-junit=build/coverage/phpunit.junit.xml || exit
  - travis_retry timeout -k 60s 30s vendor/bin/infection --min-msi=69 --threads=$(nproc) --coverage=build/coverage

after_success:
  - composer require php-coveralls/php-coveralls:^2
  - vendor/bin/php-coveralls -v
