notifications:
  email: false

addons:
  apt:
    packages:
      - stunnel4

language: php

php:
  - 7.3
  - 7.4
  - 8.0

env:
  matrix:
    -
    - DEPENDENCIES=--prefer-lowest

matrix:
  fast_finish: true

cache:
  directories:
    - vendor

install:
  - composer validate
  - composer --no-interaction update --no-progress --no-suggest $DEPENDENCIES

script:
  - XDEBUG_MODE=coverage composer test -- --coverage-clover=build/logs/clover.xml

after_success:
  - composer require php-coveralls/php-coveralls:^2
  - vendor/bin/php-coveralls -v
